[package]
name = "pincushion-rs"
version = "0.0.0"
edition = "2018"
publish = false

[[bin]]
name = "input"
path = "src/bin/input/main.rs"

[dependencies]
input-linux = "0.4.0"
nats = "0.9.2"
rmp = "0.8.10"
rmp-serde = "0.15.4"
serde = { version = "1.0.123", features = ["derive"] }
